name: CICD
on: [push]

env:
  DB_URL: postgresql://user:pass@127.0.0.1:5432/db
  S3_ENDPOINT_URL: http://127.0.0.1:8000
  S3_ACCESS_KEY_ID: access_key_id
  S3_SECRET_ACCESS_KEY: secret_access_key
  S3_REGION: ru-central1
  S3_BUCKET: bucket

jobs:
  test:
    runs-on: ubuntu-20.04

    services:

      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 1s
          --health-retries 10

      s3:
        image: zenko/cloudserver:latest-8.2
        env:
          SCALITY_ACCESS_KEY_ID: access_key_id
          SCALITY_SECRET_ACCESS_KEY: secret_access_key
          REMOTE_MANAGEMENT_DISABLE: 1
        ports:
          - 8000:8000


    steps:
      - uses: actions/checkout@v2
      - name: "Setup python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: pip install poetry
      - run: make install
      - run: make lint
      - run: make test
      - run: make cov
